app:
  scheduler:
    enable: false
    interval: 1m
    force-check-delay: 1d
    old-link-time: 1h

  database-access-type: jpa

  github-client:
    base-url: https://api.github.com
    backoff:
      max-attempts: 10
      wait-time: 1s
      type: linear
      codes:
        - internal_server_error
        - bad_gateway
        - service_unavailable
        - gateway_timeout

  stackoverflow-client:
    base-url: https://api.stackexchange.com
    backoff:
      max-attempts: 5
      wait-time: 5s
      type: exponential
      codes:
        - internal_server_error
        - bad_gateway
        - service_unavailable
        - gateway_timeout

  bot-client:
    base-url: http://localhost:8090
    backoff:
      max-attempts: 3
      wait-time: 2s
      type: constant
      codes:
        - internal_server_error
        - bad_gateway
        - service_unavailable
        - gateway_timeout

  rate-limit:
    capacity: 100
    refill-rate: 100
    refill-time: 1h
    cache-size: 10_000
    expire-time: 2h

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
